version: "3.1"

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: teambuying
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
