name: CI Pipeline

on:
  pull_request:
    branches:
      - '*' # Trigger for pull requests on all branches
  push:
    branches:
      - '*' # Trigger for pushes on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Frontend
        run: |
          cd front-end
          npm install
          npm run build

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Start MySQL with Docker Compose
        run: |
          docker-compose up -d
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            docker exec $(docker ps -q -f name=your_mysql_service_name) mysqladmin ping -h localhost -u root --password=yourpassword && break
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Build Backend
        run: |
          cd back-end
          ./mvnw clean install
